'''Cyber Risk Correlation Engine

Aggregates findings from Attack Surface Mapping (ASM), DPI analysis, and Threat Detection
into a unified risk score, correlated findings and potential attack paths.
'''\n\nfrom __future__ import annotations\n\nfrom typing import Any, Dict, List, Tuple\n\n\nclass RiskCorrelationEngine:\n    """Core engine for correlating security assessment data."""\n\n    def __init__(\n        self,\n        asm_data: Dict[str, Any] | None = None,\n        dpi_data: Dict[str, Any] | None = None,\n        threat_data: Dict[str, Any] | None = None,\n    ) -> None:\n        # Normalise inputs – they may be ``None`` when the user selects only a subset.\n        self.asm = asm_data or {}\n        self.dpi = dpi_data or {}\n        self.threat = threat_data or {}\n        # Internal containers for produced artefacts\n        self.correlated_findings: List[Dict[str, Any]] = []\n        self.attack_paths: List[Dict[str, Any]] = []\n\n    # ---------------------------------------------------------------------\n    # Helper utilities\n    # ---------------------------------------------------------------------\n    @staticmethod\n    def _make_finding(\n        title: str,\n        risk_level: str,\n        evidence: str,\n        rationale: str,\n        recommendation: str,\n    ) -> Dict[str, Any]:\n        return {\n            "title": title,\n            "risk_level": risk_level,\n            "evidence": evidence,\n            "rationale": rationale,\n            "recommendation": recommendation,\n        }\n\n    @staticmethod\n    def _make_attack_path(\n        risk_level: str,\n        evidence: str,\n        why: str,\n        recommendation: str,\n    ) -> Dict[str, Any]:\n        return {\n            "risk_level": risk_level,\n            "evidence": evidence,\n            "why": why,\n            "recommendation": recommendation,\n        }\n\n    # ---------------------------------------------------------------------\n    # Correlation logic – deliberately simple but extensible\n    # ---------------------------------------------------------------------\n    def _rule_web_exposure_missing_headers(self) -> None:\n        """Rule 1 – Open web service + missing security headers.
\n        If the ASM data reports an open TCP port that is likely a web service\n        (port 80, 443, 8080, 8443) **and** the header analysis indicates missing\n        required security headers, we raise a ``Medium`` correlated finding.
        """\n        open_ports = self.asm.get("open_ports", [])\n        missing = self.asm.get("missing_headers", [])\n        if not open_ports or not missing:\n            return\n        web_ports = {80, 443, 8080, 8443}\n        has_web = any(p.get("port") in web_ports for p in open_ports)\n        if has_web:\n            title = "Web service exposed without required security headers"\n            evidence = f"Open web‑related ports {', '.join(str(p.get('port')) for p in open_ports if p.get('port') in web_ports)}; missing headers: {', '.join(missing)}"\n            rationale = "A public web service without protective HTTP headers increases exploitable surface."\n            recommendation = "Add the missing headers (e.g., Content‑Security‑Policy, X‑Frame‑Options)."\n            self.correlated_findings.append(\n                self._make_finding(title, "Medium", evidence, rationale, recommendation)\n            )\n\n    def _rule_high_asm_and_suspicious_dpi(self) -> None:\n        """Rule 2 – High ASM finding + suspicious DPI traffic.
\n        When ASM summary reports a high severity finding **and** the DPI threat\n        summary also reports a high severity finding, we elevate the risk to\n        ``High`` for the combined observation.
        """\n        asm_summary = self.asm.get("summary", {})\n        dpi_threat = self.threat.get("threat_summary", {})\n        if asm_summary.get("high", 0) > 0 and dpi_threat.get("high", 0) > 0:\n            title = "High severity findings in both attack surface and traffic analysis"\n            evidence = f"ASM high: {asm_summary.get('high')} | DPI high: {dpi_threat.get('high')}"\n            rationale = "Concurrent high‑severity observations across layers suggest a serious risk."\n            recommendation = "Prioritise remediation of the high‑severity findings in both reports."\n            self.correlated_findings.append(\n                self._make_finding(title, "High", evidence, rationale, recommendation)\n            )\n\n    def _rule_multiple_related_findings(self) -> None:\n        """Rule 3 – Multiple related findings increase confidence.
\n        If more than three findings are present across ASM and DPI (any severity) we\n        generate a ``Low`` confidence correlated finding that encourages further\n        investigation.
        """\n        total_findings = (\n            len(self.asm.get("observations", [])) +\n            len(self.dpi.get("findings", [])) +\n            len(self.threat.get("findings", []))\n        )\n        if total_findings > 3:\n            title = "Multiple related observations across assessments"\n            evidence = f"Total combined findings: {total_findings}"\n            rationale = "The breadth of observations raises confidence in a systemic issue."\n            recommendation = "Perform a focused deep‑dive on the correlated areas."\n            self.correlated_findings.append(\n                self._make_finding(title, "Low", evidence, rationale, recommendation)\n            )\n\n    def _rule_isolated_finding(self) -> None:\n        """Rule 4 – Isolated finding lowers confidence.
\n        When exactly one finding exists in the whole assessment suite we create a\n        ``Low`` confidence correlated finding noting the isolation.
        """\n        total_findings = (\n            len(self.asm.get("observations", [])) +\n            len(self.dpi.get("findings", [])) +\n            len(self.threat.get("findings", []))\n        )\n        if total_findings == 1:\n            title = "Isolated finding – low correlation confidence"\n            evidence = "Only a single observation was present across all data sources."
            rationale = "Lack of supporting evidence suggests the finding may be a false positive."
            recommendation = "Validate the finding with additional scans or manual review."
            self.correlated_findings.append(\n                self._make_finding(title, "Low", evidence, rationale, recommendation)\n            )\n\n    # ---------------------------------------------------------------------\n    # Public API\n    # ---------------------------------------------------------------------\n    def correlate_findings(self) -> List[Dict[str, Any]]:\n        """Apply all correlation rules and return the list of findings."""\n        # Reset any previous results\n        self.correlated_findings.clear()\n        self._rule_web_exposure_missing_headers()\n        self._rule_high_asm_and_suspicious_dpi()\n        self._rule_multiple_related_findings()\n        self._rule_isolated_finding()\n        return self.correlated_findings\n\n    def compute_risk_score(self) -> Tuple[int, str]:\n        """Derive a 0‑100 risk score and a textual risk level.
\n        The scoring is simple: high=20, medium=10, low=5 per finding. The level is\n        determined by thresholds.
        """\n        high = sum(1 for f in self.correlated_findings if f.get("risk_level") == "High")\n        medium = sum(1 for f in self.correlated_findings if f.get("risk_level") == "Medium")\n        low = sum(1 for f in self.correlated_findings if f.get("risk_level") == "Low")\n        score = high * 20 + medium * 10 + low * 5\n        # Clamp to 0‑100\n        score = max(0, min(100, score))\n        if high >= 2:\n            level = "Critical"
        elif high == 1:\n            level = "High"
        elif medium >= 2:\n            level = "Medium"
        else:\n            level = "Low"
        return score, level\n\n    def generate_attack_paths(self) -> List[Dict[str, Any]]:\n        """Create illustrative attack paths based on correlated findings.
\n        For each correlated finding we fabricate a simple path that links the\n        observation to a potential attacker goal.
        """\n        self.attack_paths.clear()\n        for f in self.correlated_findings:\n            risk = f.get("risk_level", "Low")\n            evidence = f.get("evidence", "")\n            why = f"The finding '{f.get('title')}' indicates a possible exploitation vector."
            rec = f.get("recommendation", "")\n            self.attack_paths.append(self._make_attack_path(risk, evidence, why, rec))\n        return self.attack_paths\n\n    def summary(self) -> Dict[str, Any]:\n        """Return the full correlation summary used by UI and PDF reports."""\n        correlated = self.correlate_findings()\n        score, level = self.compute_risk_score()\n        paths = self.generate_attack_paths()\n        return {\n            "overall_score": score,\n            "risk_level": level,\n            "correlated_findings": correlated,\n            "attack_paths": paths,\n        }\n\n# End of file
